import {STORAGE_KEY,SOURCES,PROFILES,initialState,restoreState,sourceVersion,packSize,savings,answerFor,createDocument,createSlides} from './model.js';

const $=selector=>document.querySelector(selector);
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let storageAvailable=true,state=initialState();
try{state=restoreState(localStorage.getItem(STORAGE_KEY));}catch{storageAvailable=false;}
let preparing=false,prepareStep=0,job=0,undoDoc=null,pendingPatch=null,tourStep=0,heroStep=0,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,toastTimer;
const navigation=[['overview','⊞','Overview'],['sources','▤','Sources'],['assistant','✳','Assistant'],['notes','▧','Notes'],['document','W','Document'],['slides','▱','Slides'],['code','⌘','Coding lab'],['settings','≋','Settings']];
const profile=()=>PROFILES[state.profile];
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;}$('#save-state').textContent=storageAvailable?'Saved on this device':'Storage unavailable · session only';$('#save-state').classList.toggle('storage-warning',!storageAvailable);}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function modal(content){$('#dialog-content').innerHTML=content;const dialog=$('#detail-dialog');if(!dialog.open)dialog.showModal();}
function closeDialog(){$('#detail-dialog').close();}
function download(name,content){const link=document.createElement('a');const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'}));link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Downloaded a Markdown copy of your draft.');}
function head(eyebrow,title,subtitle,action=''){return `<div class="workspace-topline"><div><p class="eyebrow">${eyebrow}</p><h3>${title}</h3><p>${subtitle}</p></div>${action}</div>`;}
function empty(title='Your knowledge comes first.',description='Prepare the sample source pack, then come back to create something useful.'){return `<div class="empty-state"><span aria-hidden="true">▤</span><h4>${title}</h4><p>${description}</p><button class="button dark" data-open-tab="sources">Prepare the sample pack ↗</button></div>`;}
function render(){
  $('#workspace-nav').innerHTML=navigation.map(([tab,icon,label])=>`<button class="nav-button ${state.tab===tab?'active':''}" data-tab="${tab}" ${state.tab===tab?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}${tab==='code'?'<span class="tiny-badge">CONCEPT</span>':''}</button>`).join('');
  $('#sidebar-profile').textContent=profile().name+' profile';
  $('#offline-toggle').setAttribute('aria-checked',String(state.offline));
  $('#connection-label').textContent=state.offline?'Offline Lock':'Online mode';
  const stamp=state.preparedAt?new Date(state.preparedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'';
  $('#pack-strip').innerHTML=state.prepared?`<span>● Sample pack ready with gaps · ${state.selected.length} sources · ${packSize(state.selected)} KB illustrative · ${stamp}</span><button class="text-button" data-action="refresh" ${state.offline?'disabled':''}>Refresh pack ↻</button>`:`<span>${preparing?'◌ Preparing the fictional project…':'○ Sample pack not prepared · choose your approved sources'}</span><button class="text-button" data-open-tab="sources">${preparing?'View progress':'View sources'} ↗</button>`;
  const views={overview:overview,sources:sources,assistant:assistant,notes:notes,document:documentView,slides:slidesView,code:codeView,settings:settings};
  $('#workspace').innerHTML=`<div class="reveal">${views[state.tab]()}</div>`;
  save();
}
function navigate(tab,scroll=false){if(!navigation.some(x=>x[0]===tab))return;state.tab=tab;render();if(scroll)$('#demo').scrollIntoView({behavior:motion?'smooth':'instant'});$('#workspace').focus({preventScroll:true});}
function overview(){return head('YOUR PROJECT, WITH YOU','Good work starts here.','A fictional workshop. A very real way to explore the idea.')+`
  <div class="overview-welcome"><div><p class="eyebrow">${state.prepared?'PACKED FOR THE JOURNEY':'YOUR NEXT PROJECT'}</p><h4>${state.prepared?'Your workshop, ready to move.':'Northstar workshop'}</h4><p>${state.prepared?'Ask a question, turn the answer into a working draft, or explore the other tools. The missing pricing appendix remains visible.':'Prepare an onboarding workshop for the IT operations team. Bring the brief, a runbook, and the right questions.'}</p><button class="button dark" data-open-tab="${state.prepared?'assistant':'sources'}">${state.prepared?'Ask your CoWorker':'Prepare for offline'} <span>↗</span></button></div><div class="pack-count"><b>${state.prepared?state.selected.length:'04'}</b><span>${state.prepared?'captured sources':'proposed sources'}</span></div></div>
  <div class="section-label"><span>MAKE SOMETHING USEFUL</span><span>YOUR WORKING COPIES</span></div><div class="work-cards"><button class="work-card" data-open-tab="assistant"><span class="card-icon">✳</span><h4>Find your answer</h4><p>Ask a project question.<br>Follow the evidence.</p><span class="card-arrow">↗</span></button><button class="work-card" data-open-tab="document"><span class="card-icon">▧</span><h4>Shape the plan</h4><p>Make a draft.<br>Review a better version.</p><span class="card-arrow">↗</span></button><button class="work-card" data-open-tab="slides"><span class="card-icon">▱</span><h4>Tell the story</h4><p>Build your outline.<br>Bring the team along.</p><span class="card-arrow">↗</span></button></div><div class="info-line">↳ ${state.offline?'Offline Lock is on. Network-dependent demo actions are blocked.':'The story: prepare a pack → switch to Offline Lock → create your work.'}</div>`;}
function sources(){
  let content=head('PREPARE FOR OFFLINE','Bring the right knowledge.','Select from the fictional approved project scope.',`<button class="button dark" data-action="prepare" ${preparing||state.offline?'disabled':''}>${state.prepared?'Re-prepare pack':'Review & prepare'} ↗</button>`);
  content+=`<div class="scope-box"><span>SEARCH SCOPE <strong>Northstar / Workshop / Approved + local notes</strong></span><span>READ ONLY · NO MICROSOFT CONNECTION</span></div>`;
  content+=`<div class="source-list">${SOURCES.map(s=>`<div class="source-row"><input type="checkbox" data-source="${s.id}" id="source-${s.id}" aria-label="Include ${escape(s.title)}" ${state.selected.includes(s.id)?'checked':''} ${s.required||preparing||state.offline?'disabled':''}><span class="file-badge ${s.kind==='W'?'word':s.kind==='P'?'slide':''}">${s.kind}</span><div><h4><label for="source-${s.id}">${s.title}</label></h4><p>${s.reason}</p></div><div><span class="source-meta">${s.required?'Required':'Optional'} · ${s.size} KB · v${sourceVersion(s.id,state.refreshed).version}</span><br><button class="text-button" data-cite="${s.id}">Inspect source ↗</button></div></div>`).join('')}</div>`;
  if(preparing){const labels=['Copying approved fixtures','Extracting sample passages','Indexing sample evidence','Checking demo readiness'];content+=`<div class="preparation" aria-live="polite"><p class="eyebrow">SIMULATED PREPARATION</p><h4>${labels[prepareStep]}</h4><p>Showing the intended stages. No remote documents are being downloaded.</p><div class="progress"><span data-progress="${(prepareStep+1)*25}"></span></div><div class="stage-list"><span>Copy</span><span>Extract</span><span>Index</span><span>Check</span></div><button class="text-button" data-action="cancel-prepare">Cancel preparation</button></div>`;}
  content+=`<div class="notice"><strong>One visible gap:</strong> the pricing appendix is missing. You can prepare a workshop, but cannot substantiate a budget. ${state.prepared?'Pack status: Ready with gaps.':''}</div>`;
  if(state.offline)content+='<p class="info-line">Offline Lock prevents preparation and refresh. Your captured sample passages remain available.</p>';
  else content+=`<p class="info-line">${state.selected.length} selected · ${packSize(state.selected)} KB illustrative pack size · ${state.prepared?'Captured sample versions are available.':'You review this selection before preparation.'}</p>`;
  return content;
}
function assistant(){
  let content=head('ANSWERS WITH EVIDENCE','Ask your CoWorker.','Scripted demo responses. No local or cloud model is running.');
  if(!state.prepared)return content+empty();
  const answer=state.answer;
  content+=`<div class="chat-layout"><div><div class="chat-message"><h4><span aria-hidden="true">✳</span> CoWorker</h4><p>Your sample project pack is ready. What would you like to prepare for the workshop?</p><small>Captured sources · ${state.offline?'Offline Lock on':'Online demo mode'} · ${profile().name} profile</small></div>`;
  if(answer)content+=`<div class="chat-user">${escape(state.question)}</div><div class="chat-message"><h4>✳ ${answer.kind==='gap'?'A gap worth keeping visible':answer.kind==='unsupported'?'Outside this small demo':'From your project pack'}</h4><p>${escape(answer.text)}</p><div>${answer.citations.map(id=>`<button class="citation" data-cite="${id}" data-version="${state.refreshed?'new':'old'}">${escape(sourceVersion(id,state.refreshed).title)} ↗</button>`).join('')}</div><small>Scripted response · inspect the source to check the claim</small>${answer.kind==='answer'?'<button class="text-button" data-action="answer-note">Save answer to notes ↗</button>':''}</div>`;
  content+=`<div class="suggested"><button data-question="Help me prepare for the workshop">Prepare the workshop</button><button data-question="What are the handover checks?">Handover checks</button><button data-question="What is the workshop budget?">What’s the budget?</button></div><form class="chat-form" id="chat-form"><input id="question" aria-label="Ask a sample project question" placeholder="Ask about the workshop…" maxlength="500" required autocomplete="off"><button type="submit" aria-label="Send question">↑</button></form><p class="editor-note">Try a sample question. Other topics return an honest demo limitation.</p></div><aside class="evidence-panel"><p class="eyebrow">IN YOUR PACK</p>${SOURCES.filter(x=>state.selected.includes(x.id)).map(s=>`<button class="evidence-card" data-cite="${s.id}">${s.title}<small>v${sourceVersion(s.id,state.refreshed).version} · ${s.locator}</small></button>`).join('')}<p>Click a source to inspect its exact captured sample passage. No browser tab or live SharePoint file is opened.</p></aside></div>`;
  return content;
}
function notes(){return head('A LITTLE SPACE TO THINK','Keep the useful bits.','Editable notes. Saved in this browser only.',`<button class="button outline" data-action="download-note">Download .md ↓</button>`)+`<div class="paper"><div class="paper-label">NORTHSTAR / YOUR NOTES</div><label for="note-text" class="field-label">Your project notes</label><textarea id="note-text" class="editor-body notes-textarea" maxlength="20000">${escape(state.note)}</textarea><div class="editor-note">Synthetic data only. Browser storage is not an encrypted enterprise workspace.</div></div><p class="info-line">Notes remain available before and after preparing a pack.</p>`;}
function documentView(){
  let content=head('A WORKING COPY, ALWAYS','From knowledge to a plan.','Word-style concept editor · scripted sample content.');
  if(!state.prepared)return content+empty();
  if(!state.doc)return content+`<div class="empty-state"><span>▧</span><h4>Start with the project facts.</h4><p>Create an editable workshop plan using the captured brief and runbook. No AI generation takes place.</p><button class="button dark" data-action="create-document">Create sample draft ↗</button></div>`;
  if(state.refreshed!==state.doc.refreshed)content+='<div class="notice">The workshop brief changed after this draft was created. Your draft is preserved. Review the date against the refreshed source.</div>';
  content+=`<div class="editor-toolbar"><button class="button light" data-action="rewrite-document">✳ Review a shorter version</button><button class="button outline" data-action="undo-document" ${undoDoc?'':'disabled'}>↶ Undo</button><button class="button outline" data-action="download-document">Download .md ↓</button><span>Revision ${state.doc.revision}</span></div><div class="paper"><p class="paper-label">NORTHSTAR / WORKSHOP PLAN</p><label class="field-label" for="doc-title">Document title</label><input id="doc-title" class="editor-title" maxlength="120" value="${escape(state.doc.title)}"><label class="field-label" for="doc-body">Document content</label><textarea id="doc-body" class="editor-body" maxlength="20000">${escape(state.doc.body)}</textarea></div><p class="editor-note">This demo downloads Markdown. Editable .docx output belongs to the proposed desktop app. Original sample sources are never modified.</p>`;
  return content;
}
function slidesView(){
  let content=head('BRING THE TEAM ALONG','A story worth sharing.','Slide composer concept · five editable sample slides.');
  if(!state.prepared)return content+empty();
  if(!state.slides)return content+`<div class="empty-state"><span>▱</span><h4>Give your workshop a shape.</h4><p>Review a five-slide outline, then edit the sample storyboard. The proposed desktop app would export editable PowerPoint files.</p><button class="button dark" data-action="outline">Review sample outline ↗</button></div>`;
  const current=state.slides[state.slide];
  content+=`<div class="editor-toolbar"><button class="button outline" data-action="download-slides">Download storyboard .md ↓</button><span>Preview, not a PowerPoint renderer</span></div><div class="slide-layout"><div class="slide-thumbs" aria-label="Slide selection">${state.slides.map((s,i)=>`<button class="slide-thumb ${state.slide===i?'active':''}" data-slide="${i}" aria-label="Slide ${i+1}: ${escape(s.title)}" aria-pressed="${state.slide===i}"><b>${String(i+1).padStart(2,'0')}</b>${escape(s.title)}</button>`).join('')}</div><div><div class="slide-preview"><p class="eyebrow">NORTHSTAR / WORKSHOP</p><h4 id="slide-preview-title">${escape(current.title)}</h4><p id="slide-preview-body">${escape(current.body)}</p><small>SYNTHETIC CONCEPT · ${String(state.slide+1).padStart(2,'0')} / 05</small></div><div class="slide-controls"><button data-action="previous-slide" ${state.slide===0?'disabled':''}>← Previous</button><span>${state.slide+1} of 5</span><button data-action="next-slide" ${state.slide===4?'disabled':''}>Next →</button></div><label class="field-label" for="slide-title">Slide title</label><input class="field" id="slide-title" maxlength="90" value="${escape(current.title)}"><label class="field-label" for="slide-body">Slide text · max. 280 characters</label><textarea class="field" id="slide-body" rows="3" maxlength="280">${escape(current.body)}</textarea></div></div><p class="editor-note">Manual edits persist locally. Longer text may need splitting in a production slide composer.</p>`;
  return content;
}
function codeView(){return head('OPTIONAL EXTENSION / PROPOSED','A coding agent. A boundary.','Explore a review flow. No commands, code, or network calls are executed.')+`
  <div class="code-boundary"><span>Disposable project workspace</span><span>No access to company files</span><span>${state.offline?'Offline Lock overrides network grants':state.network?'One-task network grant · simulated':'Network denied by default'}</span></div><div class="scope-box"><span>TASK <strong>Make a small handover checklist formatter</strong></span><span>TYPE OF CHANGE: ONE FILE</span></div><div class="code-window"><div class="code-toolbar"><span>workspace / checklist.js</span><span>${state.codeApplied?'WORKING COPY':'PROPOSED DIFF'}</span></div><pre><code>${state.codeApplied?`export function checklist(items) {\n  return items.map(item =&gt;\n    '- [ ] ' + item.trim()\n  ).join('\\n');\n}`:`<span class="code-removed">- export function checklist(items) {\n-   return items.join(', ');\n- }</span>\n<span class="code-added">+ export function checklist(items) {\n+   return items.map(item =&gt;\n+     '- [ ] ' + item.trim()\n+   ).join('\\n');\n+ }</span>`}</code></pre></div>${state.codeApplied?'<div class="code-sample-result"><strong>Illustrative output</strong><br>− [ ] Confirm enrolment<br>− [ ] Validate applications<br>− [ ] Record support owner<br><small>Prewritten fixture, not an executed test.</small></div>':''}<div class="code-actions"><button class="button dark" data-action="${state.codeApplied?'undo-code':'review-code'}">${state.codeApplied?'Undo sample change':'Review proposed change'} ↗</button><button class="button outline" data-action="network" ${state.offline||state.network?'disabled':''}>${state.network?'Grant active for next sample task':'Request internet access'}</button></div><div class="audit-log"><strong>DEMO ACTIVITY</strong><br>${state.audit.length?state.audit.slice(-4).map(escape).join('<br>'):'No action yet. The proposed agent must ask before expanding its capabilities.'}</div><p class="editor-note">Production requirement: OS-enforced isolation, resource limits, scoped egress, and reviewable patches. A directory or a system prompt is not a security sandbox. No isolation is implemented by this demo.</p>`;}
function settings(){return head('FIT THE WORK TO THE MACHINE','A little control goes a long way.','Illustrative profiles. No hardware scan, benchmark, or model download.')+`
  <div class="settings-grid">${Object.entries(PROFILES).map(([id,p])=>`<button class="profile-card" data-profile="${id}" aria-pressed="${state.profile===id}"><span class="profile-symbol">${p.symbol}</span><strong>${p.name}</strong><small>${p.description}</small><span>${p.caption}${id==='balanced'?' · suggested':''}</span></button>`).join('')}</div><div class="notice green"><strong>${profile().name} profile selected.</strong> Context target: ${(state.context/1024).toFixed(0)}K tokens. CPU-thread budget: ${state.threads}. These controls change this demo’s preferences, not your computer.</div><div class="setting-row"><div><strong>Prefer European model providers</strong><small>A Mistral-family model is a candidate in the original brief. Exact model, licence, and compatibility need verification.</small></div><span class="badge">DESIGN GOAL</span></div><label class="setting-row" for="battery"><span><strong>Battery-conscious mode</strong><small>Proposed behaviour: one generation job at a time, unload idle models.</small></span><input id="battery" type="checkbox" ${state.battery?'checked':''}></label><details class="advanced"><summary>Advanced settings</summary><label class="setting-row" for="context"><span><strong>Context budget</strong><small>More context can use more memory. Profile values are illustrative.</small></span><select id="context"><option value="2048" ${state.context===2048?'selected':''}>2K tokens</option><option value="4096" ${state.context===4096?'selected':''}>4K tokens</option><option value="8192" ${state.context===8192?'selected':''}>8K tokens</option></select></label><label class="setting-row" for="threads"><span><strong>CPU thread budget: <output id="thread-value">${state.threads}</output></strong><small>A requested limit, not detected hardware.</small></span><input id="threads" type="range" min="1" max="12" value="${state.threads}"></label><div class="setting-row"><div><strong>Cloud inference fallback</strong><small>The proposed app must not silently send work to a remote model.</small></div><span class="badge">NEVER</span></div><div class="setting-row"><div><strong>Coding agent internet</strong><small>Separate, one-task approval. Offline Lock always takes precedence.</small></div><span class="badge">${state.offline?'BLOCKED':state.network?'GRANTED · DEMO':'ASK EACH TIME'}</span></div></details><p class="editor-note">Low-end compatibility is an ambition, not a measured result. The actual app must detect available resources and validate an eligible model before claiming readiness.</p><button class="text-button reset-in-settings" data-action="reset">↺ Reset all demo progress</button>`;}

function showSource(id,version){
  const refreshed=version?version==='new':state.refreshed;
  const s=sourceVersion(id,refreshed);if(!s)return;
  modal(`<p class="eyebrow">CAPTURED SAMPLE SOURCE</p><h3 id="dialog-title">${s.title}</h3><p>${escape(s.locator)}</p><blockquote>${escape(s.text)}</blockquote><p class="dialog-meta">Version ${s.version} · ${s.location}<br>Synthetic fixture · ${state.prepared?'captured in this demo':'preview before preparation'}</p><p>In the proposed app, citations would resolve to the exact downloaded source version. This sample is bundled with the website.</p><button class="button dark" data-action="close-dialog">Back to the workspace</button>`);
}
function prepareReview(){
  if(state.offline||preparing)return;
  modal(`<p class="eyebrow">YOUR SCOPE. YOUR DECISION.</p><h3 id="dialog-title">Prepare this project pack?</h3><p>${state.selected.length} fictional sources · ${packSize(state.selected)} KB illustrative total. The sample brief and runbook are required. Optional sources follow your selection.</p><div class="notice">Pricing appendix missing. Readiness will be <strong>Ready with gaps</strong>, not a complete commercial evidence pack.</div><p>This animates the preparation workflow. No Microsoft sign-in, download, encryption, indexing engine, or inference is performed.</p><div class="dialog-actions"><button class="button dark" data-action="confirm-prepare">Approve sample pack ↗</button><button class="button outline" data-action="close-dialog">Keep reviewing</button></div>`);
}
async function prepare(){
  if(state.offline||preparing)return;closeDialog();preparing=true;prepareStep=0;state.tab='sources';const currentJob=++job;render();
  for(let i=0;i<4;i++){prepareStep=i;render();await new Promise(resolve=>setTimeout(resolve,motion?680:140));if(job!==currentJob)return;}
  preparing=false;state.prepared=true;state.preparedAt=new Date().toISOString();state.answer=null;render();toast('Sample pack ready with gaps. Try Offline Lock next.');
}
function cancelPrepare(){job++;preparing=false;render();toast('Preparation cancelled. Any previously prepared pack is preserved.');}
function toggleOffline(){
  if(!state.prepared){toast('Prepare your sample source pack first.');navigate('sources');return;}
  if(preparing)cancelPrepare();state.offline=!state.offline;state.network=false;
  if(state.offline)state.audit.push('Offline Lock enabled: simulated network grants cleared.');
  render();toast(state.offline?'Offline Lock on. Preparation, refresh, and network grants are blocked.':'Online demo mode. Nothing refreshes or uploads automatically.');
}
function refreshReview(){if(state.offline||!state.prepared)return;if(state.refreshed){toast('No more changes in this scripted scenario. Your drafts remain untouched.');return;}modal(`<p class="eyebrow">EXPLICIT REFRESH / SIMULATED</p><h3 id="dialog-title">One source has changed.</h3><p>Workshop brief.docx has a new sample version. Review the captured date change before refreshing the pack.</p><div class="diff-old">v1.0 · Workshop: 14 October 2026</div><div class="diff-new">v1.1 · Workshop: 21 October 2026</div><p class="dialog-meta">Your notes, document, and slides will not be rewritten. Existing work may need a manual review.</p><button class="button dark" data-action="apply-refresh">Update sample pack ↻</button>`);}
function ask(question){const q=question.trim().slice(0,500);if(!q)return;state.question=q;state.answer=answerFor(q,state);render();}
function rewriteDocument(){
  if(!state.doc)return;
  const body=state.doc.body;const first=body.split('\n\n')[0];const replacement='Workshop purpose\nAgree on the onboarding process and name an owner for each handover step.';
  pendingPatch={revision:state.doc.revision,before:body,after:replacement+(body.includes('\n\n')?'\n\n'+body.split('\n\n').slice(1).join('\n\n'):'')};
  modal(`<p class="eyebrow">REVIEW BEFORE APPLYING</p><h3 id="dialog-title">A more direct opening.</h3><p>This scripted suggestion replaces only the first block of your working copy. Review it against your own edits.</p><div class="diff-old">${escape(first)}</div><div class="diff-new">${escape(replacement)}</div><p class="dialog-meta">Based on revision ${state.doc.revision}. Sources and the rest of your draft stay unchanged.</p><div class="dialog-actions"><button class="button dark" data-action="apply-document">Apply to working copy</button><button class="button outline" data-action="close-dialog">Keep original wording</button></div>`);
}
function applyDocument(){if(!state.doc||!pendingPatch||state.doc.revision!==pendingPatch.revision||state.doc.body!==pendingPatch.before){closeDialog();toast('The draft changed. Review a new suggestion before applying.');return;}undoDoc=structuredClone(state.doc);state.doc.body=pendingPatch.after;state.doc.revision++;pendingPatch=null;closeDialog();render();toast('Opening revised. Undo is available.');}
function outline(){modal(`<p class="eyebrow">OUTLINE BEFORE SLIDES</p><h3 id="dialog-title">A five-slide workshop story.</h3><p>1. Make the handover work.<br>2. One clear objective.<br>3. Three checks. No loose ends.<br>4. Ownership makes it complete.<br>5. Leave with a next step.</p><div class="notice green">Source-backed facts from the brief and runbook. Recommendations are labelled, and the missing budget stays missing.</div><p>Approving creates editable sample slides in this browser, not an AI-generated PowerPoint file.</p><button class="button dark" data-action="create-slides">Approve & create sample slides ↗</button>`);}
function reviewCode(){modal(`<p class="eyebrow">ONE FILE / ONE REVIEW</p><h3 id="dialog-title">Apply the sample change?</h3><p>The proposed change formats each handover item as a Markdown checklist line in <strong>workspace/checklist.js</strong>.</p><div class="notice green">Scope: one disposable sample file. No company files, secrets, installations, or system changes. ${state.network?'The one-task internet grant will be consumed without making any request.':'This task does not need internet access.'}</div><p>This button changes a demo state only. It does not execute code or create a real sandbox.</p><button class="button dark" data-action="apply-code">Apply sample change</button>`);}
function networkReview(){if(state.offline){toast('Offline Lock blocks network access.');return;}modal(`<p class="eyebrow">PURPOSE-BOUND NETWORK ACCESS</p><h3 id="dialog-title">Approve one sample task?</h3><p>Proposed purpose: read language documentation from <strong>developer.mozilla.org</strong>. Read only. No project uploads or arbitrary destinations.</p><div class="notice">A production agent would need an enforced network broker and OS isolation. This demo makes no outbound request and does not actually connect to the domain.</div><p>Grant expires after the next sample coding action, reset, page reload, or Offline Lock.</p><button class="button dark" data-action="approve-network">Approve simulated one-task grant</button>`);}
const tour=[
  {icon:'▤',title:'Bring only what matters.',text:'Start in Sources. Choose from approved sample documents, inspect why each belongs, and review the pack. The missing budget is visible from the start.',tab:'sources'},
  {icon:'◎',title:'Leave the connection behind.',text:'Prepare the pack, then switch on Offline Lock. Preparation, refresh, and coding-network grants become unavailable. Bundled sample content remains usable.',tab:'overview'},
  {icon:'✳',title:'An answer you can inspect.',text:'Ask a workshop question. Click its citation to read the captured sample passage. Ask about the budget and see the evidence gap instead of an invented number.',tab:'assistant'},
  {icon:'▧',title:'Turn the answer into work.',text:'Create a sample document, edit it, review a shorter opening, and undo. Then make a five-slide storyboard. Both export as Markdown in this concept demo.',tab:'document'},
  {icon:'⌘',title:'Explore the extra possibilities.',text:'The coding lab shows patch review and scoped internet approval without executing code. Settings demonstrate low-to-high resource profiles, with no unverified performance claims.',tab:'code'},
  {icon:'↻',title:'Reconnect on your terms.',text:'Switch off Offline Lock and refresh. Review a changed workshop date. The pack updates, while your drafts remain yours. Now try the story yourself.',tab:'sources'}
];
function showTour(){const t=tour[tourStep];navigate(t.tab,true);modal(`<p class="eyebrow">THE COWORKER WALKTHROUGH · ${tourStep+1} / ${tour.length}</p><span class="tour-icon" aria-hidden="true">${t.icon}</span><h3 id="dialog-title">${t.title}</h3><p>${t.text}</p><div class="tour-progress" aria-hidden="true">${tour.map((_,i)=>`<span class="${i===tourStep?'active':''}"></span>`).join('')}</div><div class="tour-controls"><button class="text-button" data-action="tour-previous" ${tourStep===0?'disabled':''}>← Previous</button><button class="button dark" data-action="tour-next">${tourStep===tour.length-1?'Try it yourself ↗':'Next step →'}</button></div>`);}

document.addEventListener('click',event=>{
  const button=event.target.closest('button,a[data-open-tab]');if(!button||button.disabled)return;
  if(button.dataset.tab){navigate(button.dataset.tab);return;}
  if(button.dataset.openTab){navigate(button.dataset.openTab,true);return;}
  if(button.dataset.cite){showSource(button.dataset.cite,button.dataset.version);return;}
  if(button.dataset.question){ask(button.dataset.question);return;}
  if(button.dataset.profile){const p=PROFILES[button.dataset.profile];state.profile=button.dataset.profile;state.context=p.context;state.threads=p.threads;render();toast(p.name+' profile selected. Demo preference only.');return;}
  if(button.dataset.slide!==undefined){state.slide=Number(button.dataset.slide);render();return;}
  if(button.dataset.hero!==undefined){heroStep=Number(button.dataset.hero);renderHero();return;}
  const actions={
    'close-dialog':closeDialog,
    'prepare':prepareReview,'confirm-prepare':prepare,'cancel-prepare':cancelPrepare,'offline':toggleOffline,'refresh':refreshReview,
    'apply-refresh':()=>{if(state.offline)return;state.refreshed=true;state.preparedAt=new Date().toISOString();state.answer=null;closeDialog();render();toast('Sample pack refreshed. Your drafts were preserved.');},
    'answer-note':()=>{if(!state.answer)return;state.note+='\n\n'+state.answer.text+'\nSources: '+state.answer.citations.map(id=>sourceVersion(id,state.refreshed).title+' v'+sourceVersion(id,state.refreshed).version).join('; ');state.note=state.note.slice(-20000);navigate('notes');toast('Scripted answer added to your notes.');},
    'download-note':()=>download('Northstar-notes.md',state.note),
    'create-document':()=>{state.doc=createDocument(state);undoDoc=null;render();},
    'download-document':()=>state.doc&&download('Northstar-workshop-plan.md','# '+state.doc.title+'\n\n'+state.doc.body),
    'rewrite-document':rewriteDocument,'apply-document':applyDocument,
    'undo-document':()=>{if(!undoDoc)return;state.doc={...undoDoc,revision:state.doc.revision+1};undoDoc=null;render();toast('Previous working copy restored.');},
    'outline':outline,'create-slides':()=>{state.slides=createSlides(state);state.slide=0;closeDialog();render();},
    'previous-slide':()=>{state.slide=Math.max(0,state.slide-1);render();},'next-slide':()=>{state.slide=Math.min(4,state.slide+1);render();},
    'download-slides':()=>state.slides&&download('Northstar-storyboard.md','# Northstar workshop — synthetic storyboard\n\n'+state.slides.map((s,i)=>'## '+(i+1)+'. '+s.title+'\n\n'+s.body).join('\n\n---\n\n')+'\n\nBrowser concept demo. Markdown storyboard, not a PowerPoint export.\n'),
    'review-code':reviewCode,'apply-code':()=>{state.codeApplied=true;state.network=false;state.audit.push('User reviewed and applied one sample change. No code executed.');closeDialog();render();toast('Sample working copy updated.');},
    'undo-code':()=>{state.codeApplied=false;state.network=false;state.audit.push('User restored the initial sample file. No code executed.');render();},
    'network':networkReview,'approve-network':()=>{if(state.offline)return;state.network=true;state.audit.push('One-task read-only documentation grant approved (simulation).');closeDialog();render();},
    'tour':()=>{tourStep=0;showTour();},'tour-next':()=>{if(tourStep===tour.length-1){closeDialog();navigate('sources',true);}else{tourStep++;showTour();}},'tour-previous':()=>{tourStep=Math.max(0,tourStep-1);showTour();},
    'motion':()=>{motion=!motion;renderHero();},
    'reset':()=>modal('<p class="eyebrow">START FRESH</p><h3 id="dialog-title">Reset this browser demo?</h3><p>This removes your demo notes, document, slides, preferences, and progress from this browser. Download anything you want to keep first.</p><div class="dialog-actions"><button class="button dark" data-action="confirm-reset">Reset demo</button><button class="button outline" data-action="close-dialog">Keep my work</button></div>'),
    'confirm-reset':()=>{job++;preparing=false;state=initialState();undoDoc=null;pendingPatch=null;try{localStorage.removeItem(STORAGE_KEY);}catch{}closeDialog();render();toast('Demo reset. Ready for the next tester.');}
  };actions[button.dataset.action]?.();
});
document.addEventListener('submit',event=>{if(event.target.id==='chat-form'){event.preventDefault();ask($('#question').value);}});
document.addEventListener('change',event=>{
  const el=event.target;
  if(el.dataset.source){const src=SOURCES.find(s=>s.id===el.dataset.source);if(!src||src.required||state.offline||preparing)return;state.selected=el.checked?[...new Set([...state.selected,src.id])]:state.selected.filter(x=>x!==src.id);state.prepared=false;state.answer=null;render();return;}
  if(el.id==='battery'){state.battery=el.checked;save();}
  if(el.id==='context'){state.context=Number(el.value);save();toast('Context preference saved. No model is running.');}
});
document.addEventListener('input',event=>{
  const el=event.target;
  if(['seats','replacement','seat-cost','support-cost'].includes(el.id)){renderSavings();return;}
  if(el.id==='note-text'){state.note=el.value;save();}
  if(el.id==='doc-title'&&state.doc){state.doc.title=el.value;state.doc.revision++;save();}
  if(el.id==='doc-body'&&state.doc){state.doc.body=el.value;state.doc.revision++;save();}
  if(el.id==='slide-title'&&state.slides){state.slides[state.slide].title=el.value;$('#slide-preview-title').textContent=el.value;save();}
  if(el.id==='slide-body'&&state.slides){state.slides[state.slide].body=el.value;$('#slide-preview-body').textContent=el.value;save();}
  if(el.id==='threads'){state.threads=Number(el.value);$('#thread-value').textContent=el.value;save();}
});
$('#detail-dialog').addEventListener('click',event=>{if(event.target===$('#detail-dialog')){const rect=event.target.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeDialog();}});
function renderSavings(){const result=savings($('#seats').value,$('#replacement').value,$('#seat-cost').value,$('#support-cost').value);const number=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(n);$('#seats-value').textContent=$('#seats').value;$('#replacement-value').textContent=$('#replacement').value+'%';$('#saving').innerHTML=number(result.net)+' <small>NOK</small>';$('#calculation-detail').textContent=`${result.count} seats × ${number(result.monthly)} NOK × 12 months − ${number(result.support)} NOK`;}
function renderHero(){
  const slides=[
    '<div class="hero-stage-inner"><h4>YOUR PROPOSED OFFLINE PACK</h4><div class="mini-file"><span class="file-badge word">W</span><span>Workshop brief.docx</span><span class="check">✓</span></div><div class="mini-file"><span class="file-badge">PDF</span><span>Onboarding runbook.pdf</span><span class="check">✓</span></div><div class="mini-file"><span class="file-badge slide">P</span><span>Workshop structure.pptx</span><span class="check">✓</span></div><p class="mini-prepared"><span class="status-dot"></span> Chosen by you. Prepared for later.</p></div>',
    '<div class="hero-stage-inner"><h4>OFFLINE LOCK ON · SAMPLE CONVERSATION</h4><div class="mini-question">What needs to happen at handover?</div><div class="mini-answer">Confirm enrolment, validate the apps, and record the support owner. <b>1</b><p class="mini-prepared">↳ Onboarding runbook · page 3</p></div></div>',
    '<div class="hero-stage-inner"><h4>FROM YOUR SOURCES TO A WORKING DRAFT</h4><div class="mini-draft"><h5>Let’s make the<br>handover work.</h5><p>Northstar workshop plan</p><div class="draft-rule"></div><div class="draft-rule"></div><div class="draft-rule short"></div><p class="mini-prepared">✓ Working copy · ready to review</p></div></div>'
  ];$('#hero-stage').innerHTML=slides[heroStep];document.querySelectorAll('[data-hero]').forEach(el=>{el.classList.toggle('active',Number(el.dataset.hero)===heroStep);el.setAttribute('aria-pressed',String(Number(el.dataset.hero)===heroStep));});$('#motion-toggle').textContent=motion?'Ⅱ':'▷';$('#motion-toggle').setAttribute('aria-label',motion?'Pause animation':'Play animation');
}
setInterval(()=>{if(motion&&!document.hidden){heroStep=(heroStep+1)%3;renderHero();}},4800);
render();renderHero();renderSavings();
if('serviceWorker' in navigator&&location.protocol!=='file:'){
  navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('#cache-state').textContent='Demo assets cached · revisit offline in this browser';}).catch(()=>{$('#cache-state').textContent='Offline caching unavailable · keep this tab open';});
}else $('#cache-state').textContent='Local demo · offline reload requires a supported web server';
