import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';

const base=process.env.DEMO_URL||'http://127.0.0.1:4173/AteaCoWorker/';
const launch={headless:true};
if(process.env.BROWSER_EXECUTABLE){launch.executablePath=process.env.BROWSER_EXECUTABLE;launch.args=['--no-sandbox','--disable-dev-shm-usage'];}
const browser=await chromium.launch(launch);
const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce',acceptDownloads:true});
const page=await context.newPage();
const errors=[],external=[],checks=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
page.on('request',request=>{if(new URL(request.url()).origin!==new URL(base).origin)external.push(request.url());});
const check=(name,condition=true)=>{assert.ok(condition,name);checks.push(name);console.log('PASS '+name);};
const tab=name=>page.locator(`[data-tab="${name}"]`).click();
await mkdir('artifacts',{recursive:true});
try{
  await page.goto(base,{waitUntil:'networkidle'});
  await page.waitForFunction(()=>document.querySelector('#workspace')?.textContent.includes('Good work starts here'));
  check('Landing and workspace render');
  await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
  await page.locator('.hero').screenshot({path:'artifacts/hero.png'});
  check('Reduced motion pauses hero',await page.locator('#motion-toggle').getAttribute('aria-label')==='Play animation');
  await page.locator('#offline-toggle').click();
  check('Unprepared pack cannot enter Offline Lock',await page.locator('#offline-toggle').getAttribute('aria-checked')==='false');
  await page.locator('[data-source="deck"]').uncheck();
  await page.locator('[data-action="prepare"]').click();
  await page.locator('[data-action="confirm-prepare"]').click();
  await page.waitForFunction(()=>document.querySelector('#pack-strip').textContent.includes('ready with gaps'));
  check('Selection and approved preparation produce a pack with explicit gaps',(await page.locator('#pack-strip').innerText()).includes('3 sources'));
  await page.locator('#offline-toggle').click();
  check('Offline Lock blocks refresh',await page.locator('[data-action="refresh"]').isDisabled());
  await tab('assistant');
  await page.locator('[data-question="Help me prepare for the workshop"]').click();
  check('Scripted answer contains captured date',(await page.locator('#workspace').innerText()).includes('14 October 2026'));
  await page.locator('.citation[data-cite="brief"]').click();
  check('Citation resolves to exact local fixture',(await page.locator('#detail-dialog blockquote').innerText()).includes('14 October 2026'));
  await page.keyboard.press('Escape');
  check('Escape closes the source dialog',!(await page.locator('#detail-dialog').evaluate(el=>el.open)));
  await page.locator('[data-question="What is the workshop budget?"]').click();
  check('Missing budget returns evidence gap',(await page.locator('#workspace').innerText()).includes('cannot give a supported amount'));
  await page.locator('#question').fill('<img src=x onerror=alert(1)>');
  await page.locator('#chat-form button').click();
  check('User input is rendered as text',await page.locator('.chat-user img').count()===0);
  await page.locator('#question').fill('Who is the owner?');
  await page.locator('#chat-form button').click();
  await page.locator('[data-action="answer-note"]').click();
  check('Answer can be captured as a note',(await page.locator('#note-text').inputValue()).includes('support owner'));
  await page.locator('#note-text').fill('Synthetic tester note: keep the checklist short.');
  await tab('document');
  await page.locator('[data-action="create-document"]').click();
  const original=await page.locator('#doc-body').inputValue();
  await page.locator('[data-action="rewrite-document"]').click();
  await page.locator('[data-action="apply-document"]').click();
  check('Reviewed document patch applies',await page.locator('#doc-body').inputValue()!==original);
  await page.locator('[data-action="undo-document"]').click();
  check('Undo restores original working copy',await page.locator('#doc-body').inputValue()===original);
  await page.locator('#doc-title').fill('My workshop plan');
  const downloadPromise=page.waitForEvent('download');
  await page.locator('[data-action="download-document"]').click();
  const download=await downloadPromise;
  check('Draft download has an honest Markdown extension',download.suggestedFilename().endsWith('.md'));
  await tab('slides');
  await page.locator('[data-action="outline"]').click();
  await page.locator('[data-action="create-slides"]').click();
  await page.locator('[data-action="next-slide"]').click();
  await page.locator('#slide-title').fill('A clear and useful objective.');
  check('Slide edit updates the preview',(await page.locator('#slide-preview-title').innerText())==='A clear and useful objective.');
  await tab('code');
  check('Offline Lock blocks coding network grant',await page.locator('[data-action="network"]').isDisabled());
  await page.locator('[data-action="review-code"]').click();
  await page.locator('[data-action="apply-code"]').click();
  check('Reviewed code sample state changes without execution',await page.locator('.code-sample-result').isVisible());
  await tab('settings');
  await page.locator('[data-profile="light"]').click();
  await page.locator('.advanced summary').click();
  await page.locator('#context').selectOption('4096');
  check('Performance and advanced preferences are selectable',(await page.locator('[data-profile="light"]').getAttribute('aria-pressed'))==='true');
  await page.reload({waitUntil:'networkidle'});
  check('Offline Lock persists across reload',(await page.locator('#offline-toggle').getAttribute('aria-checked'))==='true');
  await tab('notes');
  check('Notes persist across reload',(await page.locator('#note-text').inputValue()).includes('Synthetic tester note'));
  await tab('document');
  check('Document edits persist across reload',(await page.locator('#doc-title').inputValue())==='My workshop plan');
  await page.locator('#offline-toggle').click();
  await tab('code');
  await page.locator('[data-action="network"]').click();
  await page.locator('[data-action="approve-network"]').click();
  check('One-task network grant can be approved online',(await page.locator('#workspace').innerText()).includes('One-task network grant'));
  await page.reload({waitUntil:'networkidle'});
  check('Network grant is never restored after reload',(await page.locator('#workspace').innerText()).includes('Network denied by default'));
  await page.locator('[data-action="refresh"]').click();
  await page.locator('[data-action="apply-refresh"]').click();
  await tab('assistant');
  await page.locator('#question').fill('When is the workshop?');
  await page.locator('#chat-form button').click();
  check('Refresh updates captured answer date',(await page.locator('#workspace').innerText()).includes('21 October 2026'));
  await tab('document');
  check('Refresh preserves earlier working draft',(await page.locator('#doc-body').inputValue()).includes('14 October 2026'));
  check('Changed source prompts draft review',(await page.locator('.notice').innerText()).includes('changed after this draft'));
  await page.locator('#seat-cost').fill('300');
  check('Illustrative calculator has correct default net result',(await page.locator('#saving').innerText()).includes('96,000'));
  await page.locator('#replacement').fill('0');
  check('Calculator exposes negative net savings',(await page.locator('#saving').innerText()).includes('-12,000'));
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  await page.locator('#offline-toggle').click();
  await context.setOffline(true);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('#doc-title')?.value==='My workshop plan');
  check('Cached website reloads with browser network disabled');
  await tab('assistant');
  await page.locator('[data-question="What are the handover checks?"]').click();
  check('Scripted workflow remains usable with browser offline',(await page.locator('#workspace').innerText()).includes('confirm device enrolment'));
  await context.setOffline(false);
  await tab('overview');
  await page.locator('.app-shell').screenshot({path:'artifacts/workspace.png'});
  for(const width of [390,768,1440]){
    await page.setViewportSize({width,height:900});
    check(`No page overflow at ${width}px`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    for(const name of ['sources','document','slides','code','settings']){await tab(name);check(`${name} stays within ${width}px`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  }
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
  await tab('overview');
  await page.locator('.app-shell').screenshot({path:'artifacts/workspace-mobile.png'});
  check('No unexpected application or CSP console errors',errors.length===0);
  check('No third-party asset or API requests',external.length===0);
  await writeFile('artifacts/browser-report.json',JSON.stringify({base,checks,errors,externalRequests:external,browser:browser.version(),timestamp:new Date().toISOString()},null,2));
  console.log(`\n${checks.length} browser checks passed.`);
}catch(error){await page.screenshot({path:'artifacts/failure.png',fullPage:true});throw error;}
finally{await browser.close();}
