import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,restoreState,answerFor,savings,sourceVersion,packSize,createDocument,createSlides,SOURCES} from '../site/model.js';
test('unprepared pack never answers a project question',()=>assert.equal(answerFor('workshop',initialState()).kind,'missing'));
test('budget gap never fabricates a price',()=>{const s={...initialState(),prepared:true};const a=answerFor('What is the budget?',s);assert.equal(a.kind,'gap');assert.deepEqual(a.citations,['notes']);assert.doesNotMatch(a.text,/\d/);});
test('unselected optional source is not cited',()=>{const a=answerFor('budget',{...initialState(),prepared:true,selected:['brief','runbook']});assert.deepEqual(a.citations,[]);});
test('every scripted citation resolves',()=>{const s={...initialState(),prepared:true};for(const q of ['workshop','when','handover','budget'])for(const id of answerFor(q,s).citations){assert.ok(sourceVersion(id));assert.ok(s.selected.includes(id));}});
test('refresh preserves immutable older sample version',()=>{assert.match(sourceVersion('brief',false).text,/14 October/);assert.match(sourceVersion('brief',true).text,/21 October/);assert.equal(sourceVersion('brief',false).version,'1.0');assert.equal(sourceVersion('missing'),null);});
test('unknown topics admit scripted limitation',()=>assert.equal(answerFor('What is a quasar?',{...initialState(),prepared:true}).kind,'unsupported'));
test('illustrative cost arithmetic is honest about net costs',()=>{assert.equal(savings(100,30,300,12000).net,96000);assert.equal(savings(100,0,300,12000).net,-12000);assert.equal(savings(100,100,0,0).net,0);assert.equal(savings(11,15,300,0).count,1);});
test('untrusted calculator values are bounded',()=>{assert.equal(savings(-5,500,-300,-50).net,0);assert.equal(savings('bad','bad','bad','bad').net,0);});
test('invalid persistence recovers safely',()=>{assert.deepEqual(restoreState('{oops'),initialState());assert.deepEqual(restoreState('{"version":2}'),initialState());});
test('restored grants are revoked and mandatory sources retained',()=>{const s=restoreState(JSON.stringify({...initialState(),network:true,selected:[],profile:'injected'}));assert.equal(s.network,false);assert.deepEqual(s.selected,['brief','runbook']);assert.equal(s.profile,'balanced');});
test('Offline Lock cannot restore against an unprepared pack',()=>assert.equal(restoreState(JSON.stringify({...initialState(),offline:true,prepared:false})).offline,false));
test('draft and slides match captured date and remain unchanged on refresh',()=>{const state={...initialState(),prepared:true};const draft=createDocument(state),slides=createSlides(state);state.refreshed=true;assert.match(draft.body,/14 October/);assert.match(slides[0].body,/14 October/);assert.match(createDocument(state).body,/21 October/);assert.equal(slides.length,5);});
test('pack size counts only selected synthetic fixtures',()=>{assert.equal(packSize([]),0);assert.equal(packSize(['brief','runbook']),300);assert.equal(packSize(SOURCES.map(s=>s.id)),952);});
